//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace src.student
{


    public partial class enrollment
    {

        /// <summary>
        /// offeringsRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater offeringsRepeater;
    }
}
