//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace src.student
{


    public partial class payment
    {
        protected global::System.Web.UI.WebControls.HiddenField hfAmount;
        protected global::System.Web.UI.WebControls.HiddenField hfDescription;
        protected global::System.Web.UI.WebControls.HiddenField hfMethod;
        protected global::System.Web.UI.WebControls.HiddenField hfOfferingIds;
        protected global::System.Web.UI.WebControls.Button btnPay;
    }
}
