//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace src.shared
{
    public partial class LecturerLayout
    {
        protected global::src.controls.lecturer_sidebar LecturerSidebar1;
        protected global::src.controls.lecturer_topbar LecturerTopbar1;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadPlaceholder;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ScriptsPlaceholder;
    }
}
