//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace src.shared
{


    public partial class notification
    {
        /// <summary>
        /// notificationsRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater notificationsRepeater;

        /// <summary>
        /// emptyPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder emptyPanel;
    }
}
