//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace src.admin
{


    public partial class user_management
    {
        protected global::System.Web.UI.WebControls.FileUpload StudentImportFile;
        protected global::System.Web.UI.WebControls.Button UploadStudentFile;
        protected global::System.Web.UI.WebControls.DropDownList IntakeOverride;
        protected global::System.Web.UI.WebControls.Button ConfirmStudentImport;
    }
}
