//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace src.lecturer
{
    public partial class lecturer_attendance_history
    {
        protected global::System.Web.UI.WebControls.Repeater historyRepeater;
        protected global::System.Web.UI.WebControls.DropDownList courseFilterSelect;
        protected global::System.Web.UI.WebControls.Panel emptyPanel;
    }
}
