//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace src.lecturer
{
    public partial class lecturer_take_attendance
    {
        protected global::System.Web.UI.WebControls.Panel statusBanner;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statusIcon;
        protected global::System.Web.UI.WebControls.Label statusMessage;
        protected global::System.Web.UI.WebControls.Panel editableCourseFilters;
        protected global::System.Web.UI.WebControls.DropDownList academicYearSelect;
        protected global::System.Web.UI.WebControls.DropDownList semesterSelect;
        protected global::System.Web.UI.WebControls.DropDownList courseSelect;
        protected global::System.Web.UI.WebControls.Panel readOnlyCourseFilters;
        protected global::System.Web.UI.WebControls.TextBox dateInput;
        protected global::System.Web.UI.WebControls.TextBox startTimeInput;
        protected global::System.Web.UI.WebControls.TextBox endTimeInput;
        protected global::System.Web.UI.HtmlControls.HtmlButton markAllPresent;
        protected global::System.Web.UI.WebControls.LinkButton saveBtn;
        protected global::System.Web.UI.WebControls.Panel rosterPanel;
        protected global::System.Web.UI.WebControls.Repeater rosterRepeater;
        protected global::System.Web.UI.WebControls.PlaceHolder emptyPanel;
        protected global::System.Web.UI.WebControls.HiddenField attendanceData;
    }
}
