//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace src.lecturer
{


    public partial class lecturer_course_dashboard
    {
        /// <summary>
        /// modulesRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater modulesRepeater;

        /// <summary>
        /// assessmentsRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater assessmentsRepeater;

    }
}
